//auth action types
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT = "LOGOUT";

// PHOTO RELATED 
export const POST_PHOTO = "POST_PHOTO";
export const POST_PHOTO_SUCCESS = "POST_PHOTO_SUCCESS";
export const PHOTO_THUMBNAILS = "PHOTO_THUMBNAILS";
export const PHOTO_LIST = "PHOTO_LIST";
export const DELETE_PHOTO = "DELETE_PHOTO";
export const DELETE_PHOTO_SUCCESS = "DELETE_PHOTO_SUCCESS";

// TASK RELATED
export const CREATE_TASK = "CREATE_TASK";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL";
export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
// export const MARK_TASK_AS_COMPLETED = "MARK_TASK_AS_COMPLETED";
// export const MARK_TASK_AS_INCOMPLETE = "MARK_TASK_AS_INCOMPLETE";
export const TASKS_LIST = "TASKS_LIST";

// OTHERS
export const LOCATION_SUCCESS = "LOCATION_SUCCESS";
export const LOCATION_FAIL = "LOCATION_FAIL";

export const NEWS_SUCCESS = "NEWS_SUCCESS";
export const NEWS_FAIL = "NEWS_FAIL";

export const WEATHER_SUCCESS = "WEATHER_SUCCESS";
export const WEATHER_FAIL = "WEATHER_FAIL";

export const MATCH_LIST_SUCCESS = "MATCH_LIST_SUCCESS";
export const MATCH_LIST_FAIL = 'MATCH_LIST_FAIL';
export const CLEAR_MATCH_DATA = 'CLEAR_MATCH_DATA';

export const CLOTHS_SUCCESS = "CLOTHS_SUCCESS";
export const CLOTHS_FAIL = "CLOTHS_FAIL";